server:
  port: 8761

spring:
  output:
    ansi:
      enabled: always
  application:
    name: eureka-server
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888/

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false