server:
  port: 9106

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  output:
    ansi:
      enabled: always
  application:
    name: user-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      uri: mongodb://root:biday@localhost:27017/bidaydb?authSource=admin

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG

security:
  authorization: "enabled"

openapi:
  service:
    url: http://localhost:8000
  swagger-ui:
    path: /swagger-ui

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api/users/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json



