server:
  port: 9104

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  output:
    ansi:
      enabled: always
  application:
    name: product-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
      time-zone: UTC

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bidaydb
    username: root
    password: biday
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 18000000
      pool-name: HikariCP

openapi:
  service:
    url: http://localhost:8000
  swagger-ui:
    path: /swagger-ui

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api/products/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json